-- CreateEnum
CREATE TYPE "TaskType" AS ENUM ('METHODOLOGIES', 'TESTING_PREPARATION', 'DEBUG_CHECK', 'MEETING', 'OTHER');

-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "taskType" "TaskType" NOT NULL DEFAULT 'OTHER';
